apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system
spec:
  selector:
    matchLabels:
      env: dev
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - resources:
            requests:
              memory: "64Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          name: sales
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true